version: '3.9'

services:
  db:
    image: mongodb/mongodb-community-server
    ports:
      - '27017:27017'
  rabbitmq:
    image: masstransit/rabbitmq:latest
    ports:
      - "5672:5672"
      - "15672:15672"